### ISSUE TITLE
comments/notes 01 April alpha test

### ISSUE THREAD

**Issue by rachaelvphillips** [tlverse/acic2019-workshop#18]
**specific comments**
- add lrnr properties to sl3 [Reference](https://tlverse.org/sl3/reference/index.html)
- justification for imputation
- incorporate known g
- TSM for a single level

**overall comments**
- present the microwave meal (i.e., give `tmle3` the contrast you want in the means, and it can do the gradients for you)
- add visual analogs (i.e., pipeline)
- at beginning of each chapter, add macro overview of chapter
- add motivation
- send pre-workshop email to attendees including: background reading suggestions, `R` Studio Cloud access information, package installation, background survey
- SER next June, next winter in Sweden
- potentially add live code demos with `R` Studio Cloud – can use `knitr::purl` 
- let book serve as a companion to workshop materials, so attendees may reference it

**Comment by nhejazi** [comment]
As a follow-up to the meeting, we've decided to move the full text (after finishing any lingering writing) to the repository: https://github.com/tlverse/tlverse-handbook. This will serve as a comprehensive guide for the workshop materials (and the eventual handbook). For the workshop presentation, we will provide the following

* Stripped down bullet points presenting materials for each of the current chapters
* All material will be presented from the built static files for each of the chapters, no live code demos will be included/performed
* `.R` scripts corresponding to the `R` code appearing in the `.Rmd` document for each chapter

Let me know if I missed something @jeremyrcoyle @rachaelvphillips @podTockom
